### PR TITLE
Fixes Broken Redirect URL Handling & Moves Away from Cookies

### LINKED ISSUE #57: Encode Redirect URL in State to Prevent Issues with Missing Cookies
If an error occurs during the login process (e.g. too long to login, missing state, etc.), `handle_redirect_cookie()` resets the redirect cookie while on the login page that displays the error message.  It should not change the URL if the cookie is set and there is no `redirect_to` in the URL.

On a related note, why does the redirect cookie have an expiration time instead of being a session cookie?  There is no reason I can think of for it to hang around for 24 hours even if the browser is closed, nor for it to expire after 24 hours if the session is still active.  ISTM that it should be a session-duration cookie.

Alternately, the cookie could be done away with altogether, by encoding it as part of the `state` field in the authorization URL.  When the callback happens, the state field could be split back out into the state and the redirect URI.  All the cookie-specific code would go away, and the redirect URI calculation/cookie setting wouldn't have to be done on every request any more; the redirect URI would be determined on-demand.

### LINKED ISSUE #207: Redirect back to Origin page not working
Hi all,

Having a bit of an issue. Have been using 3.6.0 version for about a month after errors occurred in an earlier version.

I am able to get the member to login, however, it will only redirect back to the home page instead of going to the origin page.

Can some one help please. Under pressure from boss.

### LINKED ISSUE #233: redirect-user-back action is no longer firing after successful login
I have a site that was set up in January of this year and has been working until recently.  Authentication is still working.  New users from our OAuth provider are still getting logins created.  But role permissions are not being set.

I'm using filter '**openid-connect-generic-user-login-test**' to perform membership tests against the claim.  And then using the action '**openid-connect-generic-redirect-user-back**' to alter the user's wordpress role based on the claim results.  

By sprinkling in error_log() text I was able to determine that the **user-login-test** filter is running correctly.  But the code never makes it into the **redirect-user-back** function at all.  I've confirmed "Redirect Back to Origin Page" is checked in the configuration as per the wiki.

There's nothing unique about this implementation, the filter and action functions are in the functions.php code of the theme, I just can't figure out how to determine why the redirect-user-back action function is not being called even though everything else regarding the authentication process seems to be working.

Wordpress version:  5.5.1
OpenID Connect Generic version:  3.7.1

I know there is an update available but this used to work fine on the current version, so wanted to raise the question first before updating.  Thanks!

### LINKED ISSUE #274: After creating a new user it does not log in automatically
I log in with a user not present on WordPress, but present on the main platform. The plugin correctly creates the new user on WordPress, but after creating the user it does not log in automatically, it takes me back to the home page without having logged in.

this problem occurred after upgrading to the Versione 3.8.1
WordPress Version : 5.6.1

in the logs it writes : string(63) "Successful login for: 59cf34bd-6822-40e5-80d3-11892dce12df (97)"

so i guess this statement doesn't work: do_action( 'wp_login', $user->user_login, $user );
in \daggerhart-openid-connect-generic\includes\openid-connect-generic-client-wrapper.php line 512

how can i fix this error?

thank you so much

### PR DESCRIPTION
**Pull request by timnolte**
### All Submissions:

* [x] Have you followed the [plugin Contributing guideline](https://github.com/oidc-wp/openid-connect-generi/blob/dev/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

- Fixes #233 .
- Fixes #207 .
- Fixes #57 .
- Partial fix for #285 .
- Partial fix for #159 .
- Add Redirection via State Transient Support.

### How to test the changes in this Pull Request:

1. Add the plugin to a site.
2. Activate & configure plugin.
3. Load up the WordPress login screen or add Login button shortcode to a page.
4. Observe the redirect cookie is no longer being set.
5. Check site transients and observe that the State transients are now arrays.
6. Observe the redirect_to values match expected behavior.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.
- Fixes problems with Redirect User Back plugin setting no longer working.
- Fixes issues where redirect cookies fail to be set and rely on state.
- Fixes shortcodes to properly handle attributes.

### CODE REVIEW

**Comment by timnolte** [comment]
@daggerhart FYI, this PR should fix a bunch of open issues related to redirects not working as expected.

File: includes/openid-connect-generic-login-form.php [hunk 1]
```diff
@@ -171,21 +181,28 @@ function make_error_output( $error_code, $error_message ) {
...
+
 		$href = $this->client_wrapper->get_authentication_url( $atts );
 
-		ob_start();
-		?>
-		<div class="openid-connect-login-button" style="margin: 1em 0; text-align: center;">
-			<a class="button button-large" href="<?php print esc_url( $href ); ?>"><?php print $text; ?></a>
-		</div>
-		<?php
-		return wp_kses_post( ob_get_clean() );
```
Comment (daggerhart) [inline includes/openid-connect-generic-login-form.php:188]: I don't see anything else that is escaping the login button text, so I think we want to keep this wp_kses_post().

**Review by daggerhart — CHANGES_REQUESTED** [review]
This looks good from a code review perspective except one thing. Unless I missed it, I think we need to keep the wp_kses_post() for the login button.

File: includes/openid-connect-generic-login-form.php (hunk 1 above)
Comment (timnolte) [reply includes/openid-connect-generic-login-form.php:188]: @daggerhart so actually that seemed to be causing some issues with the output, and actually all of the WordPress Coding Standards & Static Analysis checks passed. Looking at this again however I'm not escaping the `$text` & `$href` variables any more which could actually be opened to abuse by the use of the hooks. I'll check this again as I was seeing issues with the output that was related to once of the issues opened.

Comment (timnolte) [reply includes/openid-connect-generic-login-form.php:188]: @daggerhart I've added escaping to the `$text` & `$href` variables. I can't use `wp_kses_post()` otherwise it incorrectly re-formats the supplied button `href` URL.

**Review by daggerhart — APPROVED** [review]
